### ISSUE TITLE
Design QA 1.4: Pre-launch Pass

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#11]
- [x] Apply Body Typeface (AcuminPro) to the following:
- [x] div.showcase-project-blurb
- [x] div.connect-text
- [x] div.mission-text
- [x] div.featured-project-blurb
- [x] div.event-text
- [x] div.about-text-container
- [x] div.project-full-text-container
- [x] .author =
  color: #826f69;
  margin-bottom: 24px;
  margin-top: 12px;
  font-size: .9em;
  letter-spacing: .5px;
- [x] .featured-image-stripe {
  height: 200%;
  width: 32%;
  top: -68%;
  background: rgba(255,255,255,.8);
- [x] .event-stripe-text on the Home page only:
  margin: 6.5%
- [x] .featured-project-blurb
  margin-top: 18px;
  width: 70%;
  line-height: 1.35em;
  font-size: .9em;
- [x] .event-time-line: 
  letter-spacing: .5px;
- [x] .event-text
  font-size: .9em;
  line-height: 1.5;
- [ ] Please set the font-size for the body text at a standard of .9em with 1.5 line-height around the site.
- [x] .baby-blue-parallelogram-text 
  font-size: 1.3em;
  line-height: 1.3em;
- [x] .team-member-name {
  font-size: 1.475em;
- [x] .team-member-position 
  color: #826F69;
  margin-top: 12px;
  font-size: .85em;
  letter-spacing: .25px;
  font-family: Interstate;
- [x] link the REES logo to dhrees.yale.edu
- [x] .showcase-project-blurb :  font-size: .9em;
- [x] .featured-image-stripe { background: rgba(255,255,255,.85)
- [x] .button  font-size: .8em;  (this is for Feature projects)
- [x] apply Acumin body text updates to "Mission" and "Connect"
- [x] update to .featured-image-stripe:  width: 30%
- [x] .event-stripe-day {
  font-size: 22px;
  line-height: 23px;
  margin: -21% 0%;
  text-align: center;
  font-weight: 700;
  letter-spacing: 1px;
  }
  .event-stripe-month {
  font-size: 13px;
  font-weight: 500;
  }

**Comment by duhaime** [comment]
This should be all set!
