### ISSUE TITLE
UX QA 1.2 - Nov Updates

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#18]
- [ ] **Projects landing view**: In reviewing the listing, I think it makes more sense to show a short blurb under each project title rather than Author Name. (Similar to the way the News and Event highlights are displayed on the home page). This gives the admins more of an opportunity to briefly describe the project and compel users to explore more. So can that custom field be called something like "Project blurb" and styled accordingly?

- [ ] Drop shadow behind body text content area: 1px 2px 5px rgba(76,76,76,.2)

- [ ] **Project Title** OnRollover: #EF6362
![project section](https://cloud.githubusercontent.com/assets/25487/20074267/88c433b8-a4fd-11e6-8093-eb334d059e4d.png)

- [ ] **Project Page category**: Can we set it up such that if multiple projects are marked "featured" then the feature area will display as a carousel that rotates the marked projects?

- [ ] **Project Page view**: To change the display of "Author Name" can a custom field be made available so that admins can update this?

- [ ] **Project Page**: Bg color of body text content area #FFFDFA at 100%

- [ ] For the **Home page** in the Events section, let's display events that are marked "showcase-event" and prioritize the one w/ the next forthcoming date into that slot. Once a date passes, it should automatically go to the next "showcase-event" on the calendar. That way, if admins plan several events for a semester, then they can simply mark the events they want to feature on the home page knowing that each will auto-update by date.

- [ ] **Home page:** Link the featured event to the event's page.

--------- Tweaks we can do later -------------

- [ ] **About page:** Color bg behind behind text: #FFFDFA at 100% (body text as well as personnel names)
- [ ] **Event Listing**: Rollover content background color: #FFFDFA
- [ ] **Site BG pattern**: - the beige diagonal shape can be updated to this color: #F8F2EC at 100%
- [ ] **Home Page**: Move event date on stripe down 10 px.

**Comment by duhaime** [comment]
Closing this issue given the mock changes
