### ISSUE TITLE
Project Page POST

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#27]
Project pages can be posted as "Pages" in the WP admin. Use Category tags to organize projects.

Project page consists of the following fields:
o	Title
o	Short blurb (1 sentence, < 20 words)
o	Author: Can enter multiple names in a list “Person One,” “Person Two”
o	Description Field: This is a large text field area w/ a few pre-styled options, i.e. section header, body text, link styling, etc.
o	Graphic – can be photo, visualization, or collection image. Will plan to pre-load a lot of general images into media library that users can also choose from.
o	Metadata Tags: Tag projects to enable views, i.e. “student project,” “topic modeling,” “social network” etc. 
o	URL Links for widget ("Related") that include field for Display Text and field for URL destination
o	Check box for “Featured”

-	Project Page displays all fields except for the short blurb
-	Image area can become slideshow if more than 1 image is loaded for the project
![project entry](https://cloud.githubusercontent.com/assets/25487/20498994/6ee76d38-affd-11e6-86a8-339f28d2a4dc.png)

**Comment by duhaime** [comment]
closed via #49
