### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/dh-rees#28]
- [x] Build events page type
 - [x] Turn on routing from events page cards to event page
 - [x]  Sort events by date
 - [x] Add past events for events that have gone by, listed in reverse order (most recent first and least recent last)
 - [x] Hero image should not change. Should display next upcoming event.
 - [x] The event cards should include the hero.

**Comment by mongmedia** [comment]
![full event listing](https://cloud.githubusercontent.com/assets/25487/20529342/cfba7682-b09d-11e6-902e-0b1a05267063.png)

**Comment by mongmedia** [comment]
![event post](https://cloud.githubusercontent.com/assets/25487/20529929/e543126e-b09f-11e6-97a1-e582aa9923ed.png)

**Comment by mongmedia** [comment]
![full event listing](https://cloud.githubusercontent.com/assets/25487/20530017/1620cb92-b0a0-11e6-9a60-85e39a5505e0.png)

**Comment by ghost** [comment]
Option 1:
![full event listing](https://cloud.githubusercontent.com/assets/25487/20531899/2f2ce016-b0a6-11e6-9006-bfcc80a44a05.png)

**Comment by ghost** [comment]
Option 2:

![full event listing-2](https://cloud.githubusercontent.com/assets/25487/20531924/48095ace-b0a6-11e6-923e-32c2a9a1cc88.png)
