### ISSUE TITLE
Design QA 1.2: Events Page - Desktop View

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#3]
- [x] Add header to Feature image
- [x] Add header "Upcoming Events" 
- [x] Event text box height = to Image box height
- [x] Event Title: increase height to 1.6em
- [x] Event Date-Time: increase height to 1em; margin-top 12px;
- [x] Event Description: AcuminPro Regular, 1em; #333333
- [x] Padding between images: 40 px;
- [x] Increase Date Banner width to accommodate numbers in Interstate Black. 
- [x] Line event images so they are aligned left to the Sign Up button (meaning the event text box is shortened a little.
- [x] Event-text-container: padding-right 35px;
- [x] Increase width of e-mail banner

**Comment by duhaime** [comment]
InterstateBlack (from /Fonts/InterstateMono-Black.otf) is showing up serif--should I use another InterstateBlack for the dates?

**Comment by duhaime** [comment]
This should also be all set (some values have been updated in more recent issues)
