### ISSUE TITLE
About Page: Past Members

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#51]
@duhaime 
One way to manage this is to add a check box to the author bio admin page for "Past Member." If they check the box, it simply hides their profile box from the About page.

Within the text area of the About page, we can just create a subheader that follows the about text that says "Past Members" and the admin can add the names there. Because their page will still exist in the database, they can link the name to that page.

**Comment by duhaime** [comment]
Cathy took care of this issue by creating a collaborators user, so we should be all set...
